= Azure App Dev in a Day Workshop - Spring Boot, Containers, CI/CD on Azure
Greg Hoelzer

:sectnums!:
:toc: left
:revnumber: 1.0
:revdate: 2018-02-26

This repository is the used to develop training materials for Azure App Dev in Day Workshop materials. This module/lab focuses on https://projects.spring.io/spring-boot/[Spring Boot]. The main author of _{doctitle}_ is *{author}*, MS Azure and is based on the more generalized Red Hat Spring Enablement Labs found here - https://github.com/rhoar-enablement/spring. The current version ({revnumber})  of this lab was last updated on {revdate}.

== Lab Overview

[cols="1,4", options="header"]
|===
2+|  Details
| Technology/Product | Azure Cloud Services, Spring Boot, Docker, Kubernetes
| Difficulty | 3
| Time | 4 hours
| Prerequisites | An understanding of Java application development and familiarity with Docker/Linux Containers
|===


== Introduction

This is a lab aimed at enabling JavaEE developers using Spring Boot, common frameworks and Microservices architecture to build, deploy and test their components using Docker, Kubernetes, and supporting Azure Cloud Services.  

*Clone this repo into a local working directory if you wish to perform the lab excersises*

Here is a short list for the available exercises:

* link:lab/docs/lab1-instructions.adoc[Lab 1 - **(Under Development)** Build/Test local Spring Boot Docker Container]
* link:lab/docs/lab2-instructions.adoc[Lab 2 - **(Under Development)** Create and Execute Jenkins 2.0 Build Pipeline]
* link:lab/docs/lab3-instructions.adoc[Lab 3 - **(Under Development)** Deploy Spring Boot Application & DB to Azure AKS]
