= Azure App Dev in a Day Workshop - Spring Boot, Containers, CI/CD on Azure
Greg Hoelzer

:sectnums!:
:toc: left
:revnumber: 1.0
:revdate: 2018-02-26

This repository is the used to develop training materials for Azure App Dev in Day Workshop materials. This module/lab focuses on https://projects.spring.io/spring-boot/[Spring Boot]. The main author of _{doctitle}_ is *{author}*, MS Azure and is based on the more generalized Red Hat Spring Enablement Labs found here - https://github.com/rhoar-enablement/spring. The current version ({revnumber})  of this lab was last updated on {revdate}.

== Updates in Progress to support Springboot/Azure Red Hat OpenShift Workshop

== Lab Overview

[cols="1,4", options="header"]
|===
2+|  Details
| Technology/Product | Azure Cloud Services, Spring Boot, Docker, Kubernetes
| Difficulty | 3
| Time | 4 hours
| Prerequisites | An understanding of Java application development and familiarity with Docker/Linux Containers
|===


== Introduction

This is a lab aimed at enabling JavaEE developers using Spring Boot, common frameworks and Microservices architecture to build, deploy and test their components using Docker, Kubernetes, and supporting Azure Cloud Services.  

*Clone this repo into a local working directory if you wish to perform the lab excersises*

Here is a short list for the available exercises:

* link:lab/day1-labs/00-lab-environment.md[Lab 0 - Local Environment or Azure Development VM Setup]
* link:lab/day1-labs/01-build-local-app.md[Lab 1 - Build & Test Local Springboot/Docker Application]
* link:lab/day1-labs/02-deploy-app-aks.md[Lab 2 - Deploy Spring Boot Application using Azure ACR Build and AKS]
