---
apiVersion: v1
kind: Service
metadata:
  name: product-web
  labels:
    name: product-web
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    name: product-web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  product-web-deploy
  labels:
    name:  product-web
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  product-web
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - image: gnhtspfpxdemo.azurecr.io/product-catalog:aa6
        name:  product-web-cntnr
        resources:
          requests:
            cpu: "0.5"
            memory: "1Gi"
        env:
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort:  8080
          name:  product-web
        imagePullPolicy: Always
      restartPolicy: Always
